version: '2'
services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: swim_${PLUGIN_NAME}_db
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - moodle-net

  moodle:
    image: 'bitnami/moodle:latest'
    container_name: swim_${PLUGIN_NAME}_moodle
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=swim_${PLUGIN_NAME}_db
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami'
    networks:
      - moodle-net
      - default
    ports:
      - "${MOODLE_PORT}:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

networks:
  moodle-net:
    external:
      name: moodle_moodle-net
  default:
      driver: bridge
