version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: swim_${PROCESS_NAME}_db
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD="!swim-access?"
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    networks:
      - moodle-net
    restart: always

  moodle:
    image: 'bitnami/moodle:latest'
    container_name: swim_${PROCESS_NAME}_moodle
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=swim_${PROCESS_NAME}_db
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD="!swim-access?"
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami'
    networks:
      - moodle-net
      - default
    ports:
      - "${PROCESS_PORT_MOODLE}:443"
    depends_on:
      - mariadb
    restart: always
    
  camunda:
    image: 'camunda/camunda-bpm-platform'
    container_name: swim_${PROCESS_NAME}_camunda
    volumes:
      - "camunda_data:/camunda/webapps"
      - "./tomcat-users.xml:/camunda/conf/tomcat-users.xml"
      - "./context.xml:/camunda/webapps/manager/META-INF/context.xml"
    networks:
      - moodle-net
      - default
    ports:
      - "${PROCESS_PORT_CAMUNDA}:8080"
    restart: always
          
  adminer:
    image: 'woahbase/alpine-adminer'
    container_name: swim_${PROCESS_NAME}_adminer
    networks:
      - moodle-net
      - default
    ports:
      - "${PROCESS_PORT_ADMINER}:443"
    restart: always
      
  mailhog:
    image: 'mailhog/mailhog'
    container_name: swim_${PROCESS_NAME}_mailhog
    networks:
      - moodle-net
      - default
    ports:
      - "${PROCESS_PORT_MAILHOG}:8025"
    restart: always

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  camunda_data:
    driver: local

networks:
  moodle-net:
    external:
      name: moodle_moodle-net
  default:
      driver: bridge
